### PR TITLE
Fix color to theme mapping

### PR DESCRIPTION
**Pull request by halocline**
#### What does this PR do?

Updates mapping of color namespaces in `data/color.js` to match theme.

#### Where should the reviewer start?

`data/color.js`

#### What testing has been done on this PR?

local design-system on `/foundation/colors`

#### How should this be manually tested?

`/foundation/colors`

#### What are the relevant issues?

Closes https://github.com/hpe-design/design-system/issues/1059

#### Screenshots (if appropriate)

**Before**
Screen Shot 2020-08-20 at 12 11 53 PM
Screen Shot 2020-08-20 at 12 12 00 PM

**After**
Screen Shot 2020-08-20 at 12 11 12 PM
Screen Shot 2020-08-20 at 12 11 22 PM

#### Is this change backwards compatible or is it a breaking change?
Backwards compatible.

### CODE REVIEW

**Comment by britt6612** [comment]
Did Greg confirm these colors ?

**Comment by halocline** [comment]
> Did Greg confirm these colors ?

All this PR does is map the color namespaces to the proper namespace in the theme. The color updates in the theme happened here: https://github.com/grommet/grommet-theme-hpe/pull/102#issuecomment-677802418

**Comment by britt6612** [comment]
> grommet/grommet-theme-hpe#102 (comment)

totally just commented on wrong PR lol wrong tab

**Comment by halocline** [comment]
> Not seeing any hex value coming through for validation-error -- should we remove that row?

Can you clarify what you are seeing/not seeing? validation-error was broken on production. It should be fixed by this PR.

**Comment by taysea** [comment]
> > Not seeing any hex value coming through for validation-error -- should we remove that row?
> 
> Can you clarify what you are seeing/not seeing? validation-error was broken on production. It should be fixed by this PR.

Whoops! Was looking at it wrong. Deploy looks correct.

**Pull request merged**
