### PR TITLE
Apply grommet background prop

### PR DESCRIPTION
**Pull request by taysea**
Add `background="background-back"` to Grommet component so that light theme background applies correctly.

Closes: #180 #355

### CODE REVIEW

**Comment by ShimiSun** [comment]
I think it looks OK, my only issue is while scrolling up/down the white color pops, is there a way to handle it better?

**Comment by halocline** [comment]
> I think it looks OK, my only issue is while scrolling up/down the white color pops, is there a way to handle it better?

Are you commenting on white above header / below footer? This happens in dark mode as well, correct? If I am seeing what you are, I think all sites experience this: https://www.apple.com/

**Comment by halocline** [comment]
> > I think it looks OK, my only issue is while scrolling up/down the white color pops, is there a way to handle it better?
> 
> Are you commenting on white above header / below footer? This happens in dark mode as well, correct? If I am seeing what you are, I think all sites experience this: https://www.apple.com/

I guess we would have to set the background on the <body> of the doc instead, if that's what we are going for.

**Comment by taysea** [comment]
> > > I think it looks OK, my only issue is while scrolling up/down the white color pops, is there a way to handle it better?
> > 
> > 
> > Are you commenting on white above header / below footer? This happens in dark mode as well, correct? If I am seeing what you are, I think all sites experience this: https://www.apple.com/
> 
> I guess we would have to set the background on the of the doc instead, if that's what we are going for.

I'm going to merge for now since the white background seems to be a standard behavior for scroll. If we want to adjust later for this, we can.

**Pull request merged**
