### PR TITLE
Feat/footer

### PR DESCRIPTION
**Pull request by britt6612**
## Work Included

* Implemented the footer in the home page to match designs as well as footer example
* Switched out FooterLink with NavLink 
* NavLink had all of the active and default font weights already being handled in state so it made more sense to use this for the main footer as well as the example footer. 
* Got an ESLint error from max-width on the guidelines file so went ahead and fixed that.

### Full Screen 
_with hover_
Screen Shot 2020-02-20 at 4 05 05 PM

_without hover_

Screen Shot 2020-02-20 at 4 04 22 PM

### Mobile 

Screen Shot 2020-02-20 at 4 04 49 PM

## Recommend 

If we are no longer using FootLink in our project and replacing with NavLink should we discuss weather or not we want to keep the helper FootLink in Aries core ?

### CODE REVIEW

**Comment by britt6612** [comment]
```
/Users/brittanyarchibeque/Documents/design-system/aries-site/src/pages/guidelines/about.js
  26:1  error  Line 26 exceeds the maximum line length of 80  max-len
  27:1  error  Line 27 exceeds the maximum line length of 80  max-len
  32:1  error  Line 32 exceeds the maximum line length of 80  max-len

✖ 3 problems (3 errors, 0 warnings)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aries-site@1.0.0 lint-fix: `eslint src --fix`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aries-site@1.0.0 lint-fix script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/brittanyarchibeque/.npm/_logs/2020-02-20T22_38_00_746Z-debug.log
husky > pre-commit hook failed (add --no-verify to bypass)
```

Was getting this error when trying to commit this is why I had to fix the guidelines/about page

**Comment by ShimiSun** [comment]
LGTM code wise

**Comment by halocline** [comment]
@britt6612 Is `<FooterLink />` being used anywhere else in the project? If not, can we remove it from `aries-core/src/js/components/helpers/Anchors`?

**Comment by britt6612** [comment]
No its not being used anywhere else I agree with removing it.

**Pull request merged**
