### PR TITLE
Update anchor style in theme

### LINKED ISSUE #539: Theme Update - Anchor styling
Color should be 'text' by default.

Design: https://www.figma.com/file/I7PsiUmvr7OEJ6311rBUfg/hpe-design-system-library-anchor?node-id=0%3A1

### PR DESCRIPTION
**Pull request by taysea**
Update anchor style to match what is shown here: https://www.figma.com/file/I7PsiUmvr7OEJ6311rBUfg/hpe-design-system-library-anchor?node-id=0%3A1

Some elements on the site that are currently `Anchors`, should now be plain/normalized Buttons -- these changes will come in a separate PR.

Closes #539

### CODE REVIEW

**Comment by ericsoderberghp** [comment]
Just confirming that these changes will be migrated to `grommet-theme-hpe` sometime soon.

**Comment by ShimiSun** [comment]
Why aren't we committing theses changes directly to the hpe theme?

**Comment by taysea** [comment]
> Why aren't we committing theses changes directly to the hpe theme?

We had discussed prior to use the site as a staging area for theme changes, then at the end of each sprint we'd put on PR to the grommet-theme-hpe with any changes that had been made. Discussed here: https://github.com/hpe-design/design-system/pull/504#discussion_r391802639

**Comment by taysea** [comment]
> Just confirming that these changes will be migrated to `grommet-theme-hpe` sometime soon.

Yes, there is already a PR on grommet-theme-hpe that holds all of the changes made last week. Waiting to be merged.

**Pull request merged**
